// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDT_pRZ1kGi-C1fVE6BYY-dWMhOXjrq0Pw',
    appId: '1:992882318986:web:eae25b8f2ccbeea625d773',
    messagingSenderId: '992882318986',
    projectId: 'glintapp-7971f',
    authDomain: 'glintapp-7971f.firebaseapp.com',
    storageBucket: 'glintapp-7971f.firebasestorage.app',
    measurementId: 'G-6DZ5PW8STH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBW8-tD-Wy_jdxs7QpVFZWjENNB0VY_d1g',
    appId: '1:992882318986:android:b5842cb31a20acb625d773',
    messagingSenderId: '992882318986',
    projectId: 'glintapp-7971f',
    storageBucket: 'glintapp-7971f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBk9ZDEOMSKDp_JxVzvtbdBQrBG1nPpeto',
    appId: '1:992882318986:ios:eaaa56b3eda6dde825d773',
    messagingSenderId: '992882318986',
    projectId: 'glintapp-7971f',
    storageBucket: 'glintapp-7971f.firebasestorage.app',
    iosBundleId: 'com.bricksbits.glintFrontend',
  );
}
